### PR TITLE
Fix loading when a dependencies key doesn't exist

### PR DESCRIPTION
**Pull request by shadow-light**
This package requires both dependencies and devDependencies to exist, else will fail to load. This is not a requirement in npm. vuetify-loader is also a dependency already so should be assumed to exist rather than testing for it.

### CODE REVIEW

**Comment by KaelWD** [comment]
Currently we only apply the loader if it's been specified in package.json, similar to the way parceljs operates.

**Comment by shadow-light** [comment]
Oh I see, vuetify-loader doesn't actually need to exist for this plugin to still be useful. I've reintroduced the conditional loading.

The problem this patch is addressing is the boolean logic that requires both `dependencies` and `devDependencies` keys to exist. This is not the case in some projects. All their dependencies might be stored in only one of those keys.

Instead I've changed it to use a try statement, which will also support projects that (for whatever reason) don't have the loader in their `package.json` but do have it installed.

**Comment by johnleider** [comment]
Following up on this PR. It isn't required to be in both dep/devDep, it's `||`. With that being said I think this would help with users not having the loader installed. We should update the language on how they fix it. Thoughts?

**Comment by shadow-light** [comment]
Oh, I think maybe we're misunderstanding each other. To clarify, if the entire `devDependencies` object does not exist in `package.json` then the check in this module results in an error. Not because `vuetify-loader` isn't in `devDependencies` but because `devDependencies` itself doesn't exist.

It is the same if `dependencies` doesn't exist as well.

`api.service.pkg.devDependencies['vuetify-loader']` raises an error because `api.service.pkg.devDependencies === undefined`

**Comment by johnleider** [comment]
I think there is an easier way to do this that doesn't involve throwing any errors. I'll push that fix up momentarily.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
