### PR TITLE
fix(webpack): remove webpack js include and use transpileDependencies

### LINKED ISSUE #55: [Bug Report] vue-cli-plugin breaks babel
### Versions and Environment
**Vuetify:** 1.3.3
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Windows 10

### Steps to reproduce
Build project in modern mode 

### Expected Behavior
Legacy mode should be transpilled corectlly

### Actual Behavior
Legacy file is not transpilled with babel

### Reproduction Link
[https://github.com/lol2x/TestModernLegacy](https://github.com/lol2x/TestModernLegacy)

### PR DESCRIPTION
**Pull request by aeby**
Fixes #55

### CODE REVIEW

**Comment by aeby** [comment]
The problem was that by setting an `include` for the `config.module.rule('js')` rule, vuetify was the only match. All other JS files were not processed (by the `babel-loader in the case of #55).

**Comment by albertlinga** [comment]
@aeby I'm getting this issue when i do npm run serve after this fix.

Error: webpack-internal:///./node_modules/core-js/modules/_is-object.js:5
  module.exports = function (it) {
                 ^
  TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

**Comment by albertlinga** [comment]
I think removing the include for the rule fixed it. No need to transpile dependency

**Comment by aeby** [comment]
@albertlinga: I don't know where your error comes from. How does your `vue.congig.js` looks like? I think the transpile dependency is needed because otherwise the included Vuetify components don't get transpiled. I guess that was the reason they added the `include` in the first place in 7fef6454b8a2b7a6c6898b7264418e34539f424e.

**Comment by albertlinga** [comment]
@aeby 

module.exports= {
  transpileDependency: ['vuetify']
}

So what I did to fix this was to remove vue.config.js in my node_modules/vue-cli-plugin-vuetify/index.js  I applied your fix but without the transpileDependency and it worked.

**Comment by aeby** [comment]
@albertlinga That's strange because I test if `vuetify` is already in the transpileDependency option: https://github.com/vuetifyjs/vue-cli-plugin-vuetify/blob/a6f664dbefa68db1ad7042b7454cb20875c5a399/index.js#L12 
If that is the case it does nothing. So in your case it should do nothing and have no effect.

**Comment by albertlinga** [comment]
@aeby  correct, the thing is adding vuetify to transpileDependency causes another issues. As mentioned in my previous comments core-js use module.exports syntax and webpack errors out because because it can't be mixed with import export syntax. 

As per https://vuetifyjs.com/en/getting-started/quick-start#ie11-support I need to add babel-polyfill which in turn depends to core-js.

**Comment by aeby** [comment]
@albertlinga I'm using the vue-cli-3 and in this case there is no need to add babel-polyfill as it's done automatically via the [cli-plugin-babel](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-babel) as explained in the linked Vuetify documentation.

> If you are using vue-cli-3, this is done automatically for you

How does your project setup looks like?

**Comment by albertlinga** [comment]
Here's what I did.

1. I created a vue project via "vue create sample"
2. Selected default template. ESLint + standard. Lint on save.
3. Added vuetify via "vue add vuetify"
4. Selected default template.
5. npm run serve
6. Open in IE11, doesn't work.
7. Go to node_modules and applied your fix in vue-cli-plugin-vuetify/index.js
8. npm run serve
9. Compiling errors out Error: webpack-internal:///./node_modules/core-js/modules/_is-object.js:5
  module.exports = function (it) {
10. I remove the logic in transpiling. 
11. npm run serve. Succeeds
12. Open in IE11, doesn't work. Errors out saying Symbol Undefined.

**Comment by aeby** [comment]
@albertlinga Ok, thanks. What vue-cli version do you use? If I run `vue create sample` I get `❯ default (babel, eslint)` and therefore babel is already included. I then did all the steps until 8 and it worked in IE11.

**Comment by albertlinga** [comment]
@aeby I am using vue cli 3 as well, installed a couple of weeks ako.

**Comment by albertlinga** [comment]
@johnleider the removal of line 11 to 15, in the chainwebpack made babel to properly transpile main.js and all files it imports downline. As explained in my comments above, without removing those lines, as soon as I add vuetify to a vue app, even if i add babel-polyfill depndency and import it in main.js webpack is unable to transpile modern javascript syntax to the ones compatible with IE11. If you'll look at the error in browser console es6 syntax such as arrow functions from main.js is still present. E.g.render: h => h(App). Others like ES7 function shorthand syntax in App.vue and Helloworld.vue, i.e. data () ... was not transpiled as well.

@aeby i don't think you should do anything with transpileDependency. Manually adding vue.config.js in the project and specifying dependencies to transpile in there is already supported if need be.

**Comment by KaelWD** [comment]
This causes `yarn build --mode development` to fail with `Cannot assign to read only property 'exports' of object '#<Object>'`, but if you downgrade `@vue/cli-plugin-babel` and `@vue/cli-service` to 3.0.5 then it works fine.

**Comment by adamorlowskipoland** [comment]
Guys I have no idea what is going on in here. Look:

When I add:``
    if (opts.transpileDependencies.indexOf('vuetify') === -1) {
      opts.transpileDependencies.push('vuetify')
    `}`

Then I have following error: 
image

If I don't add above code, then the app doesn't run on EDGE and IE11 :( 

Any ideas?

**Comment by adamorlowskipoland** [comment]
> Here's what I did.
> 
> 1. I created a vue project via "vue create sample"
> 2. Selected default template. ESLint + standard. Lint on save.
> 3. Added vuetify via "vue add vuetify"
> 4. Selected default template.
> 5. npm run serve
> 6. Open in IE11, doesn't work.
> 7. Go to node_modules and applied your fix in vue-cli-plugin-vuetify/index.js
> 8. npm run serve
> 9. Compiling errors out Error: webpack-internal:///./node_modules/core-js/modules/_is-object.js:5
>    module.exports = function (it) {
> 10. I remove the logic in transpiling.
> 11. npm run serve. Succeeds
> 12. Open in IE11, doesn't work. Errors out saying Symbol Undefined.
> 13. npm install --save 'babel-polyfill'
> 14. add impot 'babel-polyfill' in my main.js
> 15. npm run serve.
> 16. Open in IE11 now works.


Hi,
Everything worked for me after having those versions:


    "vuetify": "^1.3.0",
    "@vue/cli-plugin-babel": "^3.1.1",

Then my steps was:
> 1. I created a vue project via "vue create sample"
> 2. Selected default template. ESLint + standard. Lint on save.
> 3. Added vuetify via "vue add vuetify"
> 4. Selected default template.
> 5. npm run serve
> 6. Open in IE11, doesn't work.
> 7. npm install --save babel-polyfill
> 8.in my main.js add import 'babel-polyfill'
> 9. npm run serve.
> 10. Open in IE11 now works.

Hope that help someone. I spent 2 days solving the issue.

@albertlinga thank you for contribution

**Comment by Aymkdn** [comment]
If we add `import 'babel-polyfill'` in `main.js` then *all* the polyfills are added (it means 80kb of polyfill).

I don't understand why we should have `transpileDependencies: ['vuetify']` in combination with `import 'babel-polyfill'` ?
I thought the point of having `transpileDependencies: ['vuetify']` is to have `node_modules/vuetify` compiled, and to have the required polyfills added on-the-fly.... no ?

> transpileDependencies
>
> By default babel-loader ignores all files inside `node_modules`. If you want to explicitly transpile a dependency with Babel, you can list it in this option.
> https://cli.vuejs.org/config/#transpiledependencies

So... there is no magical way to only include the polyfills required by Vuetify to make it work with IE11, and we're stuck with the 80kb of polyfills ?

**Comment by johnleider** [comment]
I have a fix going up for this. Your implementation of modifying the opts.transpileDependencies won't actually work.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by sneko** [comment]
Hi @johnleider ,

I have a "weird" issue with Vue SSR. I think that's due to transpilation since the error is just on runtime when serving pages. I would be interested to have your thoughts about it!

I described it on https://github.com/vuetifyjs/vuetify-loader/issues/143 

Thank you,

**Pull request closed without merging**
